[book]
authors = ["Thomas Graves"]
language = "en"
multilingual = false
src = "src"
title = "AWFUL SECURITY NEWS"

[output.html]
theme = "src/theme"
default-theme = "ayu"
mathjax-support = true
no-section-label = true
additional-js = ["src/theme/elasticsearch-search.js"]
additional-css = ["src/theme/elasticsearch-search.css"]

[output.html.search]
enable = false
